
apiVersion: v1
kind: Pod
metadata:
  name: vault-k8s-auth
  labels:
    app: vault-k8s-auth
spec:
  nodeSelector:
    role: worker
  serviceAccountName: vault-app-auth
  containers:
    - name: app
      command:
        - tail
        - "-f"
        - /dev/null
      image: ankur6ue/vault_k8s_auth
      envFrom:
        - configMapRef:
            # ensure you have created this cm using k create cm vault-k8s-auth --from-env-file=vault_settings.cfg
            name: vault-k8s-auth

      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "256Mi"
          cpu: "1000m"
